### ISSUE TITLE
Touring Carriages support

### ISSUE THREAD

**Issue by manguz** [ArranzCNL/ImprovedCameraSE-NG#16]
I love TC mod, but IC is messing up player cart camera.
Could you please make something like detect TC sitting animation on cart and disable IC for that situation?
Cheers

**Comment by ArranzCNL** [comment]
It should be working ok at least it has been on my playthrough(s), possibly that it is just fixed due to the current dev branch (v1.1.0) which will be released on the 26/04/2024.

Also you should be able to switch views either via toggling pov switch or just using the mouse scroll wheel.
