### ISSUE TITLE
Something i noticed that may help with the crafting station bug

### ISSUE THREAD

**Issue by sarcreem** [ArranzCNL/ImprovedCameraSE-NG#21]
Going in and out of first person in combat confuses OAR into thinking you are in first person while in third person and third person while in first person. Instead of using the OAR files or something it reverts to "First person project" in the OAR logging whilst in third person. This makes it so first person animations are used in third person, not allowing mods like adxp mco from continuing their combos, and breaking all animations like sleeping in go to bed, skyclimb, and i suspect crafting and whatnot.

https://youtu.be/5I2_mfEE03Q?si=UHZmVVCBKAjo1EUV At 1:18 is where the switch happens and you can notice that the projects used for animations are switched when in third person and in first person, breaking a lot of things

With this, I am uninstalling, thank you for the otherwise great mod.

**Comment by ArranzCNL** [comment]
I am sorry but what does this have to do with Improved Camera SE?

How animation works... it sends animation graphs to both first person (arms model) and third person (player model) vice versa is still running when in relevant camera states. This is why when I switch on the player model flag (make it visible) you are able to see basic animation playing with the player model whilst in first person. This isn't the case for FO4, T-Pose occurs as animation graph for the player model isn't sent when in first person likewise with arms (first person) not sent in third person. (This one somewhat works but is extremely buggy).

Personally I have seen no issues with OAR what I have heard problems about in regards to this are issues in regards to ADXP MCO which obviously needs to update their logic behind this, afaik source code is not available. They simply just need to check the model flag for visibility should be enough.

Either way there is nothing we as the community can do about this unless someone creates their own ADXP MCO open sourced  just like what happened with DAR.

**Comment by sarcreem** [comment]
This is the case since after i uninstalled improved camera se, the mistaken switch of third person being used in first person and vice versa stopped happening in combat and animations that stopped responding worked. Theres no problem with ADXP MCO and OAR, it just confuses the game in the project its supposed to be using which i thought would be helpful in your search to perfecting this mod. Look at 1:18 in the vid and look at the project in the top right of oar logging and youll see the info im trying to relay to you.

**Comment by ArranzCNL** [comment]
As I previously stated I haven't encountered issues with OAR... just reports on ADXP MCO acting weird (this was before OAR came out) and there is nothing I can do about this since source code is unavailable, If I don't know how it works how can I fix the issue!?

If you look at the first few seconds in on your video it is using third person animations in first person until you switch your weapons which is coming from ADXP.
