### ISSUE TITLE
Bug-Projectiles-HEADBOB

### ISSUE THREAD

**Issue by DeclineDawn** [ArranzCNL/ImprovedCameraSE-NG#9]
Hi ArranzCNL
I'm making a mod that adds and remakes a lot of weapons based on staves and crossbows in Skyrim.
-https://www.youtube.com/watch?v=XCG00A0vd7s&t=3s
-https://www.youtube.com/watch?v=Ryt4n7wi6xA&t=217s

Your Improved Camera mod really has great potential!!!.

I planned all my new animations for 3rd person to be done with priority for use in the game Improved Camera SE.
But I discovered a strange bug in the behavior of projectiles when the HEADBOB- setting is enabled.
(Video1-Magic)-https://drive.google.com/file/d/1eoMdOI-SDYWOrKCl4rRRZRoTWV5gtlKQ/view?usp=sharing)
(Video2-Crossbow)-(https://drive.google.com/file/d/1DJGQj2nB__uRX9WEDWzoO5bMLgGDO1rG/view?usp=sharing)
All projectiles flying from 1st person when HEADBOB is turned on do not fly out of the player’s hands, but fly out from above, to the left, from behind the player’s back and do not hit the target.
This breaks all thrown weapons and magic in Skyrim.
Please tell me what the problem might be and how it can be fixed?
I really love ImprovedCamera and want to develop it with my animations.

**Comment by ArranzCNL** [comment]
It is a known issue with headbob combat, magic is completely out of whack and noticed bow was still misaligned. It will be fixed somepoint in the future just cannot get the displacement values correct to realign the projectiles/magic for this mode currently.

**Comment by DeclineDawn** [comment]
> It is a known issue with headbob combat, magic is completely out of whack and noticed bow was still misaligned. It will be fixed somepoint in the future just cannot get the displacement values correct to realign the projectiles/magic for this mode currently.

Please tell me why in the HEADBOB mode the position of the projectiles generally shifts?
In vanilla, projectiles for magic, crossbows and bows always fly out of the bones of NPC R MagicNode [RMag] and NPC L MagicNode [LMag], and the camera only indicates the direction of flight of the projectiles.
In HEADBOB everything looks very strange... 
Effects in the hands when shooting work normally on the bones NPC R MagicNode [RMag] and NPC L MagicNode [LMag], which means the position of the bones does not change.
BUT the projectiles fly out from a distorted position.
I already corrected something similar in the vanilla skyrim.ini file for bows and crossbows.
In skyrim.ini there is the following data in the settings:
[Combat]
f1PArrowTiltUpAngle=2.5
f3PArrowTiltUpAngle=2.0
f1PBoltTiltUpAngle=2.5
f3PBoltTiltUpAngle=2.0
These vanilla settings shift the position of the fired projectile but do not affect the position of the NPC R MagicNode [RMag] and NPC L MagicNode [LMag] bones.
It looks like turning on HEADBOB triggers a similar shift in the position of the projectiles.

**Comment by ArranzCNL** [comment]
It shifts due to headbob mode is not a natural/vanilla mode for first person in turn means I need to fix but I don't know how currently as my initial attempts just fail to realign for magic at least.

**Comment by DeclineDawn** [comment]
> It shifts due to headbob mode is not a natural/vanilla mode for first person in turn means I need to fix but I don't know how currently as my initial attempts just fail to realign for magic at least.

Tell me, why do you use the NPC COM [COM] bone to attach skeletons?
The fact is that the NPC COM [COM] bone from the 3rd person has an animation and disabling or blocking it will lead to a violation of the behavior of the animation from the 3rd person.
It is because of this that the body’s legs slide along the ground when HEADBOB is turned off. .
The 3rd person NPC COM [COM] bone is best left untouched.
For attachment, it is better to use the root bone NPC Root [Root].
This will allow a 3rd person body attached to a 1st person NPC Root [Root] bone to use the animated NPC COM [COM] bone, and then the legs will not slide on the ground.

**Comment by ArranzCNL** [comment]
I can tell you haven't look at the source code as the node which is captured is the topmost NPC... not NPC COM [COM], NPC COM [COM] is also a child node of NPC Root [Root] which means it would update even in that situation due to where the node is located,

I haven't tested maybe using the NPC Eyebone but there is a problem here with Vampire Lord naming it NPC Eyebrow unless that is an XP32 error :/

Edit:
Thanks for pointing out about COM [COM] need see if can work around that somehow, might be able to just use this and move the position and it will retain its current data without getting reset from its parent, will have to experiment.

**Comment by DeclineDawn** [comment]
Yes, of course I didn't look at the source code. I don't know how it's possible to see this.
Unfortunately, scripts and programming are my biggest pain point.
I can work with models, textures, animations, sounds, behavior and everything else, BUT I’m very stupid in scripts.
Therefore, in development, I always try to rely on talented scripters like you.

If you bypass the NPC COM [COM] bone for the 3rd person and use other bones such as NPC and NPC Root [Root] that do not use animation, and are located in zero initial coordinates, then this can fix the bug with sliding legs near the body when turned off with HEADBOB disabled.
And then you won’t have to turn on HEADBOB so that your feet don’t slide on the ground and then the projectiles will work correctly.

Please let me know the results of your experiments.
I'm currently making animation for the 3rd person and I want to make this animation for a beautiful, smooth display of the body with your mod.
But due to a bug with sliding legs near the body from the 3rd person when HEADBOB is turned off, as well as because of a bug with projectiles with HEADBOB, I cannot continue working with the new animation.

**Comment by DeclineDawn** [comment]
Hi Arranz
I tested the old version of the Skyrim mod - Enhanced Camera for LE from LogicDragon, released in 2016.
https://www.nexusmods.com/skyrim/mods/57859
To my surprise, when connecting HEADBOB in this mod, all projectiles fly correctly.
How can it be?
Yes, there the place where the shot effects are reproduced is just as shifted as in your Improved Camera SE, but the projectiles fly correctly.
Perhaps you should check the code of this Skyrim - Enhanced Camera plugin and use the same settings to adjust the location of projectiles and effects in your ImprovedCameraSE.

**Comment by ArranzCNL** [comment]
Current workaround for 1.1.0 is disabling headbob whilst in combat.
